name: Archive GCC Linux Executable

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -G Ninja

      - name: Build
        run: cmake --build build --parallel

      - name: Archive Release GCC Linux Executable
        uses: actions/upload-artifact@v2
        with:
          name: clovis-release-gcc-linux
          path: build/bin/Release/clovis
