name: Clovis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # =========================================================
  # Build Job
  # =========================================================
  build:
    runs-on: ${{ matrix.platform[1] }}

    strategy:
      matrix:
        platform:
          - [windows, windows-latest, msvc, Debug]
          - [windows, windows-latest, msvc, Release]
          - [windows, windows-latest, gcc, Debug]
          - [windows, windows-latest, gcc, Release]
          - [windows, windows-latest, clang-cl, Debug]
          - [windows, windows-latest, clang-cl, Release]
          - [linux, ubuntu-latest, gcc, Debug]
          - [linux, ubuntu-latest, gcc, Release]
          - [linux, ubuntu-latest, clang, Debug]
          - [linux, ubuntu-latest, clang, Release]

    env:
      OPERATING_SYSTEM: ${{ matrix.platform[0] }}
      DISTRIBUTION: ${{ matrix.platform[1] }}
      COMPILER: ${{ matrix.platform[2] }}
      BUILD_TYPE: ${{ matrix.platform[3] }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Clang
      if: env.COMPILER == 'clang'
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "17.0"

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Configure
      shell: bash
      run: |
        if [ "${{ env.COMPILER }}" == "msvc" ]; then
          cmake -S . -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -G "Visual Studio 17 2022" -DWARNINGS_AS_ERRORS=ON
        elif [ "${{ env.COMPILER }}" == "clang-cl" ]; then
          cmake -S . -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -G "Visual Studio 17 2022" -T ClangCL
        elif [ "${{ env.COMPILER }}" == "clang" ]; then
          cmake -S . -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -G Ninja -DCMAKE_CXX_COMPILER=clang++ -DWARNINGS_AS_ERRORS=ON
        elif [ "${{ env.COMPILER }}" == "gcc" ]; then
          cmake -S . -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -G Ninja -DCMAKE_CXX_COMPILER=g++ -DWARNINGS_AS_ERRORS=ON
        fi

    - name: Build
      run: cmake --build build --parallel --config ${{ env.BUILD_TYPE }}

    - name: Test
      run: ctest --test-dir build --build-config ${{ env.BUILD_TYPE }} --output-on-failure

    - name: Bench
      shell: bash
      env: 
        EXPECTED: 149143481
      run: |
        ./build/bin/$BUILD_TYPE/bench ./utilities/bench/bench.csv > output
        cat output
        ACTUAL=$(grep -o 'bench:[[:space:]]*[0-9][0-9]*' output | grep -o '[0-9][0-9]*')
        echo "Actual ${ACTUAL} Expected ${EXPECTED}"
        [[ "$ACTUAL" == "$EXPECTED" ]] || exit 1

    - name: Perft
      if: env.BUILD_TYPE == 'Release'
      shell: bash
      run: | 
        set -e # Exit immediately if a command exits with a non-zero status
        ./build/bin/$BUILD_TYPE/perft ./utilities/perft/perft.epd

    - name: IQ
      shell: bash
      run: ./build/bin/$BUILD_TYPE/iq ./utilities/iq/iq.epd

  # =========================================================
  # Self Play Job
  # =========================================================
  self-play:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Configure
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -G Ninja -DBUILD_TESTS=OFF -DBUILD_UTILITIES=OFF

    - name: Build
      run: cmake --build build --parallel --config debug

    - name: Checkout cutechess
      uses: actions/checkout@v4
      with:
        repository: cutechess/cutechess
        path: cutechess
        ref: master
        persist-credentials: false

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qtbase5-dev qt5-qmake libqt5svg5-dev
    
    - name: Build cutechess
      working-directory: cutechess
      run: |
        mkdir build
        cd build
        cmake ..
        make -j
    
    - name: Download clovis-release-gcc-linux artifact
      run: |
        curl -L -o build/clovis-release-gcc-linux https://github.com/jonathanmcdermid/Clovis/releases/download/III/clovis-release-gcc-linux
        chmod +x build/clovis-release-gcc-linux
    
    - name: Self-play
      shell: bash
      working-directory: cutechess
      run: |
        set -e
        ./build/cutechess-cli \
          -engine name=clovis-new cmd="../build/bin/Release/clovis" \
          -engine name=clovis-old cmd="../build/clovis-release-gcc-linux" \
          -each proto=uci tc=inf/5+0.1 \
          -games 2 -rounds 200 -repeat 2 -maxmoves 200 \
          -sprt elo0=0 elo1=10 alpha=0.05 beta=0.05 \
          -concurrency 32 \
          -resultformat "results - %s wins, %s draws, %s losses" > results.log
        
        cat results.log
      
        los_line=$(grep "LOS:" results.log)
        echo "LOS line: $los_line"
        
        los_percentage=$(echo "$los_line" | awk '{print $7}' | tr -d '%')
        echo "LOS percentage: $los_percentage"
        
        if [ $(echo "$los_percentage < 5.0" | bc) -eq 1 ]; then
          echo "Error: Likelihood of superiority (LOS) is less than 10%."
          exit 1
        fi

  # =========================================================
  # Clang Format Job
  # =========================================================
  clang-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up clang-format
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format

    - name: Check code formatting
      run: find src \( -name '*.cpp' -o -name '*.h' \) -exec clang-format -Werror --style=file -n {} +

  # =========================================================
  # Editor Config Job
  # =========================================================
  editorconfig:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install editorconfig-checker
      uses: editorconfig-checker/action-editorconfig-checker@main

    - name: Check CMakeLists.txt formatting
      run: find . \( -name 'CMakeLists.txt' \) -exec editorconfig-checker {} \+ || { echo "EditorConfig check failed!"; exit 1; }

    - name: Check C++ formatting
      run: find src \( -name '*.cpp' -o -name '*.hpp' \) -exec editorconfig-checker {} \+ || { echo "EditorConfig check failed!"; exit 1; }

  # =========================================================
  # Clang Tidy Job
  # =========================================================
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "17.0"

      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Static code analysis
        run: |
          cmake -S . -B build -DCMAKE_CXX_CLANG_TIDY=clang-tidy -DCMAKE_BUILD_TYPE=Debug -G Ninja -DCMAKE_CXX_COMPILER=clang++
          cmake --build build --parallel --config Debug
  
  # =========================================================
  # Code Coverage Job
  # =========================================================
  code-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Install GCC Coverage
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr

    - name: Configure
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -G Ninja -DCOVERAGE=ON -DBUILD_UTILITIES=OFF

    - name: Build
      run: cmake --build build --parallel --config debug

    - name: Run Tests
      run: cd build && ctest && cd ..

    - name: Generate HTML code coverage reports
      run: | 
        mkdir build/code-coverage
        gcovr -r ./src/ ./build/ --exclude='.*/test/.*' --exclude='.*/dynamic_library/.*' --exclude='.*/version.h' --html --html-details -o ./build/code-coverage/index.html
    
    - name: Coverage visualization in pipeline summary
      run: gcovr -r ./src/ ./build/ --exclude='.*/test/.*' --exclude='.*/dynamic_library/.*' --exclude='.*/version.h' --exclude-unreachable-branches --print-summary -o ./build/coverage.xml

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.3.0
      with:
        name: code-coverage
        path: |
          build/code-coverage
          build/coverage.xml
